### ISSUE TITLE
修出新bug了www

### ISSUE THREAD

**Issue by De1taZer0** [TwoBotFramework/TwoBot#1]
![image](https://user-images.githubusercontent.com/110798233/183361529-46ae8f8e-42a1-4fe2-8239-478951f18a89.png)

**Comment by ScSofts** [comment]
？

**Comment by ScSofts** [comment]
可以请你再websocket那边加个dump吗😂

**Comment by ScSofts** [comment]
![image](https://user-images.githubusercontent.com/51468689/183362832-7b91ca52-b0a4-43e4-b4a5-10064c46fa30.png)

**Comment by De1taZer0** [comment]
我试试

**Comment by ScSofts** [comment]
![B%%`1 $CXAAU$G_F)_6`}CH](https://user-images.githubusercontent.com/51468689/183362995-e45ba77d-ec95-4a11-aee8-3c71bc50c9d7.png)
我这里没有任何问题

**Comment by ScSofts** [comment]
![VDS0L7$OD 3_AU)KUP@S(OS](https://user-images.githubusercontent.com/51468689/183363397-3d967b90-1c8d-46ef-83f0-eb1d7127788e.png)
emoji也没问题
![image](https://user-images.githubusercontent.com/51468689/183363496-1cda0750-d87f-4cf2-bae7-52e9088148bf.png)

**Comment by ScSofts** [comment]
好的我知道了，websocket应该给个空值

**Comment by De1taZer0** [comment]
![image](https://user-images.githubusercontent.com/110798233/183363718-1528b372-6db2-43fd-b22f-0f723e38ff11.png)

**Comment by ScSofts** [comment]
你pull下看看😂

**Comment by ScSofts** [comment]
怎么样

**Comment by De1taZer0** [comment]
没装git  在装了在装了（）

**Comment by ScSofts** [comment]
> 没装git 在装了在装了（）

没问题，我发了新release

**Comment by ScSofts** [comment]
众所周知的原因，用git可能会有点慢😂

**Comment by De1taZer0** [comment]
好了好了 正常了www 谢谢
