### ISSUE TITLE
事件的设置好像有点问题ww

### ISSUE THREAD

**Issue by De1taZer0** [TwoBotFramework/TwoBot#3]
**今天做了下 bot 的戳一戳
然后翻了翻 twobot.hh 看见了 GroupNotifyNotice
一开始我是这么写的：**
![image](https://user-images.githubusercontent.com/110798233/183840216-425b5250-de62-453a-9a78-26fa34b0a709.png)

**发现根本没有反应**

**然后我在第一个 if 前加了个 cout
又试了试 结果 cout 也没有触发**
**然后我就把 onebot 服务端的 log_level 改成了 Debug
看了下戳一戳的事件**
![P HB~(E{OXJ Z1L{3ZFC`IV](https://user-images.githubusercontent.com/110798233/183840659-b2c7702d-d386-4ba0-b988-42c504c9d277.png)
**我看里面的 notice_type 是 group**

**于是我就试着把 twobot.hh 里的 GroupNotifyNotice 中 "group_notify" 改成了 "group"**
![image](https://user-images.githubusercontent.com/110798233/183840921-c4b11af1-6321-4b1f-ab76-060276131d23.png)

**然后又把 twobot.cc 里 if 的条件也改成了 group**
![image](https://user-images.githubusercontent.com/110798233/183841234-eac5fad0-6cfc-4776-82bf-29757ae90f2f.png)

**现在 bot 就能正常反应了**
![6F358F7D1D9D38B2632A91456607F684](https://user-images.githubusercontent.com/110798233/183841466-e22a2a8e-0a57-4b63-8cc7-050d8b38480a.jpg)

**然后我又测试了下**
![C0) 6E)2GEVKCMP4T87O4RI](https://user-images.githubusercontent.com/110798233/183841639-daa64cea-64d2-4488-87fe-21b423a1e221.png)
**上传文件是 "message" "group"**

![RM8{S~%J5B`Z)LX37RCLLTP](https://user-images.githubusercontent.com/110798233/183841743-047847f8-4e9f-4f59-8861-781fa41e922a.png)
**禁言是 "notice" "group" 禁言时间是其中的 duration 单位是秒**

**而解除禁言只是把 duration 设置成 0**
![`B1F() VSG$S%W9`_GRC%1](https://user-images.githubusercontent.com/110798233/183841975-634b805a-24f6-4dd9-bc10-7c592c29a554.png)

![9ABHBS~1RPJF`WV$ Q}{T@J](https://user-images.githubusercontent.com/110798233/183842241-45f5b27d-e0cf-4709-b4d2-7262226d5c66.png)
**管理员也是 "notice" "group"**

**别的还没测试..**

**顺便问一下 bot 怎么在群里拍别人 用 CQ:poke 太怪了**
![B636B388D08CC8C84B4A2A36B10A698A](https://user-images.githubusercontent.com/110798233/183842637-7465dfa4-928f-4110-a8bd-f48b6b23dc21.jpg)
**这是私聊的戳一戳吧（）**
**原来能发到群里吗www**

**Comment by ScSofts** [comment]
建议看我b站的专栏，你没有开启cq_http模式，使用的是不标准的onebot

**Comment by De1taZer0** [comment]
草 原来是我的问题吗 ()

**Comment by ScSofts** [comment]
我的实现完全按照onebot，迁移到go-cqhttp也只是改配置的事情，但是如果妥协了OICQ不标准的onebot，就不好用了

**Comment by ScSofts** [comment]
再次感谢您的支持
