### ISSUE TITLE
bot发消息存在大概2s延迟

### ISSUE THREAD

**Issue by A1ephHuang** [TwoBotFramework/TwoBot#4]
是我的环境问题吗 如何解决

**Comment by ScSofts** [comment]
建议先直接用postman请求api看看有没有延迟😂具体什么情况我这边也不知道呀

**Comment by A1ephHuang** [comment]
就是 sendGroupMsg 这句 不管发送什么消息都有 2s 左右的延迟

**Comment by ScSofts** [comment]
> 就是 sendGroupMsg 这句 不管发送什么消息都有 2s 左右的延迟

明白😂，你修改修改配置文件，最好API调用频率限制，印象中oicq默认是500ms，你可以改小一点比如5ms

**Comment by ScSofts** [comment]
理论上我这个库100%没问题，我已经经过各种测试了

**Comment by ScSofts** [comment]
实在不行，几个onebot server轮着试试😂

**Comment by A1ephHuang** [comment]
破案了，我把127.0.0.1改成localhost了）
